In [16]:
import numpy as np
from numpy.linalg import norm
from numpy import sqrt, log2, sum

In [3]:
## ex1
M = np.array([[1, 2, 3, 4, 5, 6, 7],
              [4, 1, 3, 2, 5, 6, 7],
              [2, 5, 1, 1, 3, 6, 9],
              [2, 3, 4, 1, 1, 6, 8],
              [3, 2, 1, 1, 4, 6, 7]])

In [14]:
def cos_sim(a, b):
    dot_a_b = a @ b
    norm_a = norm(a)
    norm_b = norm(b)
    return dot_a_b / (norm_a*norm_b)

In [15]:
## 1-1
cos_sim(M[0], M[1])

0.95

In [ ]:
def PMI(x: int, c: int, M):
    x_num = sum(M[x])
    c_num = sum(M[:, c])
    x_c_num = M[x, c]
    num = sum(M)
    return log2((x_c_num*num)/(x_num*c_num))

In [18]:
## 1-2

for j in range(len(M[0])):
    print(PMI(2, j, M))

-0.29545588352617136
0.910994993941255
-1.2954558835261714
-0.8804183842473275
-0.29545588352617136
-0.0324214776923775
0.21150410519371182


In [27]:
## 1-3
P = np.array([[float(0) for i in range(len(M[0]))] for i in range(len(M))])
for i in range(len(M)):
    for j in range(len(M[0])):
        pmi = PMI(i, j, M)
        if pmi > 0:
            P[i][j] = pmi
        else:
            P[i][j] = 0
P

array([[0.        , 0.        , 0.2370392 , 1.0671142 , 0.38904229,
        0.        , 0.        ],
       [0.6520767 , 0.        , 0.2370392 , 0.0671142 , 0.38904229,
        0.        , 0.        ],
       [0.        , 0.91099499, 0.        , 0.        , 0.        ,
        0.        , 0.21150411],
       [0.        , 0.28506071, 0.81557543, 0.        , 0.        ,
        0.07860983, 0.15261042],
       [0.45943162, 0.        , 0.        , 0.        , 0.28950662,
        0.13750352, 0.01885903]])

In [28]:
cos_sim(P[0], P[1])

0.30139189091153046

In [31]:
## 1-4
max_cos_sim = 0
for a in range(len(P)):
    for b in range(a+1, len(P)):
        pair_sim = cos_sim(P[a], P[b])
        if pair_sim > max_cos_sim:
            print(a, b, pair_sim)
            max_cos_sim = pair_sim

0 1 0.30139189091153046
1 4 0.921292090269977


In [32]:
## ex2
W = np.array([[3, 3, 2, 1, 2, 6],
              [1, 7, 1, 5, 1, 1]])

X = np.array([[6, 1, 3, 1, 1, 5],
              [1, 1, 3, 2, 7, 1],
              [1, 5, 2, 6, 1, 1]])

In [40]:
## 2-1
W @ np.concatenate([X[:, 0], X[:, 1]])

array([56, 25])

In [41]:
## 2-2
Y_1 = np.array([0 for i in range(len(X[0]) - 1)])
for i in range(len(X[0]) - 1):
    Y_1[i] = (W @ np.concatenate([X[:, i], X[:, i+1]]))[0]
Y_1

array([56, 37, 63, 42, 39])

In [45]:
## 2-3
# calc Y
Y = np.array([[0 for i in range(len(X[0]) - 1)] for i in range(len(W))])
for i in range(len(X[0]) - 1):
    Y_i_j = W @ np.concatenate([X[:, i], X[:, i+1]])
    Y[0][i] = Y_i_j[0]
    Y[1][i] = Y_i_j[1]
    
# max pooling
Y_max = np.array([0 for i in range(len(W))])
for i in range(len(Y_max)):
    Y_max[i] = np.max(Y[i])

Y_max

array([63, 78])

In [56]:
## ex3
H = np.array([[1.0, 0.2, -0.8, 0.2],
              [-0.2, 2.2, 1.2, 0.5]])

z1 = np.array([[0.1],
               [-0.2]])

z2 = np.array([[-0.4],
                [0.6]])

In [50]:
def softmax(a: np.ndarray):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    softmaxed_a = exp_a / sum_exp_a
    return softmaxed_a

In [54]:
H @ softmax(H.T @ z1)

array([[0.25614499],
       [0.73725499]])

In [58]:
H @ softmax(H.T @ z2)

array([[-0.08965867],
       [ 1.41550016]])